version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.43.1
    steps:
      - checkout
      - run:
          name: setup
          command: |
            rustup component add rustfmt clippy
            rustup install nightly
      - run:
          name: cargo build
          command: |
            cargo --version --verbose
            cargo build
      - run:
          name: cargo fmt
          command: |
            cargo fmt --version
            cargo fmt -- --check
      - run:
          name: cargo test
          command: |
            cargo test
      - run:
          name: cargo clippy
          command: |
            cargo clean
            cargo clippy -- -D warnings
      - run:
          name: "Check 'no std' build"
          command: |
            cargo +nightly --version --verbose
            cargo +nightly check --no-default-features
      - run:
          name: Check JS build
          command: |
            # install npm + yarn + wasm-pack
            sudo apt install npm
            curl -o- -L https://yarnpkg.com/install.sh | bash
            export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
            curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
            # test js package build
            cd js && yarn
            yarn build
            yarn test
workflows:
  version: 2
  run-build:
    jobs:
      - build
