version: 2.1
commands:
  build-js:
    steps:
      - run:
          name: Js install + Build
          command: |
            # install npm + yarn + wasm-pack
            sudo apt install npm
            curl -o- -L https://yarnpkg.com/install.sh | bash
            export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
            curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
            # buidl
            cd js && yarn build
  test-js:
    steps:
      - run:
          name: Js Test
          command: |
            # set PATH env var- not carrying over :/
            export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
            cd js && yarn && yarn test
jobs:
  build:
    docker:
      - image: circleci/rust:1.43.1
    steps:
      - checkout
      - run:
          name: cargo check
          command: |
            cargo --version --verbose
            cargo check
      - run:
          name: cargo fmt
          command: |
            cargo fmt --version
            cargo fmt -- --check
      - run:
          name: cargo test
          command: |
            cargo test
      - run:
          name: "Check 'no std' build"
          command: |
            cargo --version --verbose
            cargo check --no-default-features
      # JS
      - build-js
      - test-js
  publish-js:
    docker:
      - image: circleci/rust:1.43.1
    steps:
      - checkout
      - build-js
      - run:
          name: Publish to NPM
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_KEY}" > ~/.npmrc
            cd js
            # node vs npm versions are funny
            npm uninstall -g npm
            # Yank old package versions
            npm unpublish @plugnet/doughnut-wasm@0.0.1-dev.0
            npm unpublish @plugnet/doughnut-wasm@0.0.1-dev.1
            npm unpublish @plugnet/doughnut-wasm@0.0.1
  clippy:
    docker:
      - image: circleci/rust:1.43.1
    steps:
      - checkout
      - run:
          name: cargo clippy
          command: |
            rustup component add rustfmt clippy
            cargo clippy -- -D warnings
workflows:
  version: 2
  run-build:
    jobs:
      - build
      - clippy
      # only publish to npm on release branch
      - publish-js:
          requires:
          - build
          - clippy
          filters:
            branches:
              only:
                - /^[0-9]+[.][0-9]+[.][0-9](-[a-zA-Z].+)?$/
