name: "Install dependencies"
description: "Prepare repository and all dependencies"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@1.73
      with:
        toolchain: nightly-x86_64-unknown-linux-gnu
        target: wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - name: Install Node.js LTS
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'yarn'
        cache-dependency-path: js/yarn.lock
    - name: Install JS deps
      run: yarn install --frozen-lockfile
      working-directory: js
    - name: Install wasm-pack
      run: yarn global add wasm-pack
    - name: Build JS wasm library using wasm-pack
      run: yarn build
      working-directory: js