name: Publish to Crates.io

on:
  workflow_dispatch:

# Note: The `doughtnut-js` package version is based on the `js/Cargo.toml` file.
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.73
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Publish to Crates.io
        run: cargo publish
        env:
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
