name: Publish to Crates.io

on:
  workflow_dispatch:

jobs:
  publish-crate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.73
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Publish to Crates.io
        run: cargo publish --token $CARGO_REGISTRY_TOKEN
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
